#!/bin/sh
# Pre-commit hook to run RSpec tests before committing

# Run RSpec tests
echo "Running Unit tests..."
rake test

# Check the status of the tests
if [ $? -ne 0 ]; then
  echo "Unit tests failed. Commit aborted."
  exit 1
fi

echo "Unit tests passed."
